const Colors = {
  navbarBackgroundColor: '#2c3e50',
  statusBarColor: '#2c3e50',
  navbarIconColor: '#bdbcca',
  alertButtonTextColor: '#000000',
  alertTitleTextColor:"#FFFFFF",
  alertButtonBackgroundColor: '#FFFFFF',
  buttonBackgroundColor:'#3a3a54',
  white:'#ffffff',
  blue:'#0000FF',
  darkSkyBlue:'#165bd6',
  mainBackgroundColor:'#f0f0f6',
  navbarTitleColor:'#57b0fc',
  borderColor:'#c4c4cb',
  textBackgroundColor:'#f0f0f6',
  subTextColor:'#696969',
  buttonBackgroundColor:'#3b3954',
  buttonTextColor:'#fdfdfd',
  signBackgroundColor:'#e7e7e7',
  rowBackgroundColor:'#f4f4f4',
  indexBackGroundColor:'#41415b',
  grayTextColor:'#808080',
  placeholderTextColor:'#447cdc',
  loginBackgroundColor:'#f9fafc',
  green:'#1bda2e',
  red:'#FF0000',

};

export default Colors;
