const Colors = {
  navbarBackgroundColor: '#2c3e50',
  statusBarColor: '#2c3e50',
  navbarIconColor: '#bdbcca',
  alertButtonTextColor: '#000000',
  alertTitleTextColor:"#FFFFFF",
  alertButtonBackgroundColor: '#FFFFFF',
  buttonBackgroundColor:'#3a3a54',
  white:'#ffffff',
  blue:'#0000FF',
  darkSkyBlue:'#185DD7',
  mainBackgroundColor:'#f0f0f6',
  navbarTitleColor:'#57b0fc',
  borderColor:'#000000',
  textBackgroundColor:'#f0eff5',
  textBackgroundColor1:'#F5F6FA',
  subTextColor:'#4D4F5C',
  buttonBackgroundColor:'#3b3954',
  buttonTextColor:'#fdfdfd',
  signBackgroundColor:'#e7e7e7',
  rowBackgroundColor:'#f4f4f4',
  indexBackGroundColor:'#41415b',
  grayTextColor:'#808080',
  placeholderTextColor:'#447cdc',
  loginBackgroundColor:'#f9fafc',
  green:'#1bda2e',
  red:'#FF0000',
  lightborderColor:'#A5A4BF',
  lightBackgroundColor:'#f4f4f4',
  gray:'#d6d6d5',
  lightgreen:'#cde7cc',
  lightPink:'#ffccd0',
  darkPink:'#ffaba9',
  aash:'#f8f9fb',
  lightBlueTitleColor:'#57b0fc',
  black:'#000000',
  scanBackground:'#F8FAFB',

};

export default Colors;
