import {Dimensions} from 'react-native';


export const SCREEN_WIDTH = Dimensions.get('window').width;
export const SCREEN_HEIGHT = Dimensions.get('window').height;
export const TEXT_MARGIN_TOP = 6;
export const SECTION_MARGIN_TOP = 20;
export const COLUMN_PADDING= 10;
export const TEXT_PADDING_LEFT= 5;
export const TEXT_PADDING_RIGHT= 5;
export const FIELD_MARGIN_TOP= 10;
export const MAIN_BLOCK_BORDER_RADIUS= 10;
export const SHORT_BLOCK_BORDER_RADIUS= 5;
export const SHORT_BORDER_RADIUS= 3;
export const TEXT_FIELD_HIEGHT= 40;
export const MAIN_VIEW_PADDING= 20;
export const BORDER_WIDTH= 1;
export const SHORT_BORDER_WIDTH= .5;
export const SHORT_BUTTON_HEIGHT= 30;
export const SIGNATURE_VIEW_HEIGHT= 150;
export const ADDRESS_FIELD_HEIGHT= 100;
export const CREDIT_FIELD_HEIGHT= 200;
export const TOTAL_BLOCK= 240;
export const ORDER_BLOCK= 300;
export const SHORT_TEXT_FIELD_HIEGHT= 30;
export const AMOUNT_BLOCK_HIEGHT= 80;
export const ORDER_BLOCK_HIEGHT= 120;
export const NORMAL_FONT= 12;
export const SECOND_FONT= 14;
export const THIRD_FONT= 16;
export const FOURTH_FONT= 18;
export const SIXTH_FONT= 22;
export const CAMERA_SIZE= 50;
export const LOGIN_FIELD_HEIGHT= 60;
